/**
 * Per-execution chat run scope. Generated by `ChatPanel.handleSend` at
 * user-submit time and threaded through `sendMessage → orch.execute →
 * graph config.configurable.runScope`.
 *
 * Lives in `config.configurable.runScope` (core) and `chatSessionStore.activeRun`
 * (ui), never on long-lived state — see `chat-streaming-ux/spec.md` Requirement
 * "Chat events and store actions enforce run-level isolation".
 *
 * `threadId` is the product-layer `chat_threads.thread_id` resolved from
 * `OfficeSessionState.selectedThreadId` at submit time; it is the same value
 * embedded in the middle segment of `conversationKey` (`<projectId>::<threadId>::<employeeId?>`).
 * It is duplicated here so downstream consumers (deliverables, SOP runtime,
 * activity log, interaction-follow-up) can scope by thread without parsing
 * `conversationKey`.
 */
import type { ChatAttachmentRef } from './chat-attachments.js';

export interface RunScope {
  readonly conversationKey: string;
  readonly runId: string;
  readonly threadId: string;
  /**
   * Chat attachment refs persisted at user-submit time. Boss / manager /
   * employee nodes inherit these on dispatch and rebuild their gateway-lane
   * current-turn system preface from them. Empty when the user sent a text-only
   * turn.
   */
  readonly pendingAttachments?: readonly ChatAttachmentRef[];
  /**
   * Recent same-thread attachment refs from earlier user messages. These are
   * readable by `read_attachment` under the same `(companyId, threadId)` scope,
   * but they are not considered newly submitted files and must not trigger SDK
   * lane pre-flight blocking by themselves.
   */
  readonly availableAttachments?: readonly ChatAttachmentRef[];
}

/**
 * Project a `RunScope` into the optional event-payload fields the
 * chat-affecting payload types carry (`chatConversationKey` + `chatRunId` +
 * `chatThreadId`). Returns an empty object when scope is absent so callers
 * can spread unconditionally.
 *
 * `chatThreadId` is the product-layer `chat_threads.thread_id`; downstream
 * consumers (deliverable feed, activity log, interaction follow-up) use it
 * to land events on the correct thread's right rail without parsing the
 * conversationKey middle segment.
 */
export function chatScopeFields(
  runScope?: RunScope | null,
): { chatConversationKey?: string; chatRunId?: string; chatThreadId?: string } {
  if (!runScope) return {};
  return {
    chatConversationKey: runScope.conversationKey,
    chatRunId: runScope.runId,
    chatThreadId: runScope.threadId,
  };
}
