/**
 * Per-execution chat run scope. Generated by `ChatPanel.handleSend` at
 * user-submit time and threaded through `sendMessage → orch.execute →
 * graph config.configurable.runScope`.
 *
 * Lives in `config.configurable.runScope` (core) and `chatSessionStore.activeRun`
 * (ui), never on long-lived state — see `chat-streaming-ux/spec.md` Requirement
 * "Chat events and store actions enforce run-level isolation".
 *
 * `threadId` is the product-layer `chat_threads.thread_id` resolved from
 * `OfficeSessionState.selectedThreadId` at submit time; it is the same value
 * embedded in the middle segment of `conversationKey` (`<projectId>::<threadId>::<employeeId?>`).
 * It is duplicated here so downstream consumers (deliverables, SOP runtime,
 * activity log, interaction-follow-up) can scope by thread without parsing
 * `conversationKey`.
 */
export interface RunScope {
  readonly conversationKey: string;
  readonly runId: string;
  readonly threadId: string;
}

/**
 * Project a `RunScope` into the optional event-payload fields the five
 * chat-affecting payload types carry (`chatConversationKey` + `chatRunId`).
 * Returns an empty object when scope is absent so callers can spread
 * unconditionally.
 */
export function chatScopeFields(
  runScope?: RunScope | null,
): { chatConversationKey?: string; chatRunId?: string } {
  if (!runScope) return {};
  return {
    chatConversationKey: runScope.conversationKey,
    chatRunId: runScope.runId,
  };
}
