use std::{env, fs, path::Path};

fn main() {
    emit_kanban_state_machine();
    tauri_build::build()
}

fn emit_kanban_state_machine() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let ssot_path = Path::new(&manifest_dir)
        .join("../../../packages/shared-types/src/kanban-state-machine.json");
    println!("cargo:rerun-if-changed={}", ssot_path.display());

    let raw = fs::read_to_string(&ssot_path).expect("read kanban-state-machine.json");
    let parsed: serde_json::Value =
        serde_json::from_str(&raw).expect("parse kanban-state-machine.json");
    let transitions = parsed
        .get("transitions")
        .and_then(serde_json::Value::as_object)
        .expect("kanban-state-machine.json transitions object");

    let mut state_names: Vec<&str> = transitions.keys().map(String::as_str).collect();
    state_names.sort_unstable();

    let mut pairs = Vec::new();
    for from in &state_names {
        let targets = transitions
            .get(*from)
            .and_then(serde_json::Value::as_array)
            .expect("kanban transition target array");
        for target in targets {
            let to = target.as_str().expect("kanban transition target string");
            pairs.push((*from, to));
        }
    }
    pairs.sort_unstable();

    let mut generated = String::new();
    generated.push_str(
        "// Generated by build.rs from packages/shared-types/src/kanban-state-machine.json.\n",
    );
    generated.push_str(&format!(
        "#[cfg(test)]\npub const KANBAN_STATE_MACHINE_JSON: &str = {:?};\n",
        raw
    ));
    generated.push_str("pub const KANBAN_STATE_NAMES: &[&str] = &[\n");
    for state in state_names {
        generated.push_str(&format!("    {:?},\n", state));
    }
    generated.push_str("];\n");
    generated.push_str("pub const KANBAN_ALLOWED_TRANSITIONS: &[(&str, &str)] = &[\n");
    for (from, to) in pairs {
        generated.push_str(&format!("    ({:?}, {:?}),\n", from, to));
    }
    generated.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(
        Path::new(&out_dir).join("kanban_state_machine.rs"),
        generated,
    )
    .expect("write generated kanban state machine");
}
