// ── Puppet animation system types ──────────────────────────────────

/** All animation states a puppet can be in */
export type PuppetAnimState =
  | 'idle'
  | 'walking'
  | 'sitting'
  | 'working'
  | 'thinking'
  | 'talking'
  | 'resting'
  | 'searching'
  | 'reporting'
  | 'excited'
  | 'blocked'
  | 'success'
  | 'failed'
  | 'paused';

/** Hair style variants for employee characters */
export type HairStyle =
  | 'short'
  | 'long'
  | 'ponytail'
  | 'curly'
  | 'bald'
  | 'bob'
  | 'spiky'
  | 'braids';

/** Body type variants */
export type BodyType = 'normal' | 'slim' | 'stocky';

/** Gender presentation (affects body proportions slightly) */
export type GenderPresentation = 'neutral' | 'masculine' | 'feminine';

/**
 * Character appearance configuration.
 * Generated by the employee creation wizard and stored alongside the employee.
 */
export interface CharacterConfig {
  readonly skinColor: number;
  readonly hairColor: number;
  readonly hairStyle: HairStyle;
  readonly clothingColor: number;
  readonly clothingAccent: number;
  readonly bodyType: BodyType;
  readonly gender: GenderPresentation;
}

// ── Puppet geometry constants ──────────────────────────────────────

/** Q-version (chibi) proportions — head:body ≈ 1:1 */
export const PUPPET = {
  /** Logical height of the full puppet (used for positioning) */
  height: 36,
  head: {
    radius: 8,
    eyeRadius: 1.5,
    eyeSpacing: 4,
    mouthWidth: 3,
  },
  body: {
    width: 12,
    height: 10,
    cornerRadius: 3,
  },
  arm: {
    width: 3,
    length: 8,
    handRadius: 2,
  },
  leg: {
    width: 3.5,
    length: 7,
    footWidth: 4,
    footHeight: 2,
    spacing: 4,
  },
} as const;

// ── Default character configs (for R&D company template) ───────────

export const DEFAULT_CHARACTER_CONFIGS: readonly CharacterConfig[] = [
  // Dev team (4)
  { skinColor: 0xf5d6b8, hairColor: 0x2c1810, hairStyle: 'short', clothingColor: 0x3b82f6, clothingAccent: 0x1d4ed8, bodyType: 'normal', gender: 'masculine' },
  { skinColor: 0xe8c4a0, hairColor: 0x1a1a2e, hairStyle: 'ponytail', clothingColor: 0x6366f1, clothingAccent: 0x4f46e5, bodyType: 'slim', gender: 'feminine' },
  { skinColor: 0xd4a574, hairColor: 0x8b4513, hairStyle: 'curly', clothingColor: 0x10b981, clothingAccent: 0x059669, bodyType: 'stocky', gender: 'masculine' },
  { skinColor: 0xf0d5c0, hairColor: 0x4a3728, hairStyle: 'spiky', clothingColor: 0x0ea5e9, clothingAccent: 0x0284c7, bodyType: 'normal', gender: 'masculine' },
  // Product team (2)
  { skinColor: 0xfce4c8, hairColor: 0x6b3a2a, hairStyle: 'bob', clothingColor: 0xa855f7, clothingAccent: 0x9333ea, bodyType: 'normal', gender: 'feminine' },
  { skinColor: 0xe8c8a0, hairColor: 0x1c1c1c, hairStyle: 'short', clothingColor: 0x8b5cf6, clothingAccent: 0x7c3aed, bodyType: 'slim', gender: 'masculine' },
  // Art team (2)
  { skinColor: 0xf5d0b0, hairColor: 0xc0392b, hairStyle: 'long', clothingColor: 0xf97316, clothingAccent: 0xea580c, bodyType: 'slim', gender: 'feminine' },
  { skinColor: 0xd2a882, hairColor: 0x5d4e37, hairStyle: 'braids', clothingColor: 0xef4444, clothingAccent: 0xdc2626, bodyType: 'normal', gender: 'neutral' },
];
