export const ALL_EVENT_TYPES = [
  'All',
  'Node',
  'Plan',
  'Task',
  'Deliverable',
  'Employee',
  'Install',
  'Skill',
  'LLM',
  'Interaction',
  'Error',
  'MCP',
  'Knowledge',
  'Meeting',
  'HR',
  'Memory',
  'Infrastructure',
  'Git',
  'Attachment',
] as const;

export type EventFilterType = (typeof ALL_EVENT_TYPES)[number];

export const TYPE_PREFIX_MAP: Record<EventFilterType, string[]> = {
  All: [],
  Node: ['graph.node.'],
  Plan: ['plan.'],
  Task: ['task.'],
  Deliverable: ['deliverable.'],
  Employee: ['employee.'],
  Install: ['install.'],
  Skill: ['skill.'],
  LLM: ['llm.'],
  Interaction: ['interaction.'],
  Error: ['error.'],
  MCP: ['mcp.'],
  Knowledge: ['knowledge.'],
  Meeting: ['meeting.', 'direct.chat.'],
  HR: ['hr.'],
  Memory: ['memory.'],
  Infrastructure: ['rack.', 'slot.', 'binding.', 'cost.'],
  Git: ['git.'],
  Attachment: ['chat.attachment.'],
};
