/**
 * Neutral multi-agent delegation contract.
 *
 * `AgentRunEvent` is the agent-agnostic vocabulary for the run tree: who
 * delegated to whom, what each run is doing, and how each run ends. It rides the
 * runtime event bus as a single `agent.run` family event whose payload is this
 * self-describing envelope (consumers switch on `payload.type`). No `pi_agent_*`
 * term crosses into this layer — the Pi host is one possible producer, never the
 * vocabulary.
 *
 * The run tree is rebuilt purely from the scope fields (`runId / parentRunId /
 * rootRunId`), so a child run can be grafted under its parent without any
 * out-of-band ordering. `rootRunId` is the user-turn run (the controller
 * `attemptId`); the root agent keeps its existing event stream and is the tree
 * root. `runId` is minted per child by the supervisor, consistent with
 * `RunScope`'s per-run identity model (see `../run-scope.ts`).
 *
 * See `Docs/DELEGATION_ARCHITECTURE.md` for the full architecture.
 */

/**
 * How a run relates to its parent — a parent-child *relation*, never a fan-out
 * shape. `delegate` hands off a bounded subtask; `review` is a check of prior
 * work. Specialist takeover (transferring the user conversation) is a later epic
 * and is intentionally NOT a relation value yet — exposing a `handoff` the
 * runtime can't honor only misleads the model. Parallel vs serial is
 * {@link DelegateExecutionMode}, not a relation.
 */
export type AgentRunRelation = 'delegate' | 'review';

/** How a delegate tool call fans out: one awaited child, or several concurrent. */
export type DelegateExecutionMode = 'single' | 'parallel';

/** Terminal + in-flight states a run can be in. */
export type AgentRunStatus = 'running' | 'completed' | 'failed' | 'cancelled';

/** Capability band a delegated run is granted. */
export type AgentRunAccess = 'read' | 'write' | 'review';

/**
 * The semantic *kind of work* a run performs — the delegate tool's operational
 * semantics, not an animation. A short enum used for employee matching, tool /
 * workspace policy, output contracts, and (downstream) dramaturgy. Optional:
 * absent means "unclassified", never a fabricated default.
 */
export type WorkKind =
  | 'plan'
  | 'research'
  | 'design'
  | 'implement'
  | 'review'
  | 'test'
  | 'compute'
  | 'publish'
  | 'present'
  | 'coordinate';

/**
 * The category of a single tool call, derived from tool *facts* (the tool name)
 * by the host/projection — never generated by the model and never parsed from
 * raw shell content. Renderers receive this safe category, not tool internals.
 */
export type ActivityKind =
  | 'read'
  | 'search'
  | 'write'
  | 'edit'
  | 'shell'
  | 'build'
  | 'test'
  | 'inspect'
  | 'wait';

export type AgentRunEventType =
  | 'run.started'
  | 'run.delta' // child token stream (content | reasoning)
  | 'tool.started'
  | 'tool.completed' // carries status: completed | failed
  | 'artifact.created'
  | 'approval.requested'
  | 'run.completed'
  | 'run.failed'
  | 'run.cancelled';

/** Rolled-up token/cost accounting for a run (and, aggregated, its subtree). */
export interface AgentRunUsage {
  readonly input?: number;
  readonly output?: number;
  readonly cacheRead?: number;
  readonly cacheWrite?: number;
  readonly cost?: number;
  readonly turns?: number;
}

/** Scope fields present on every event — the run tree is rebuilt from these. */
export interface AgentRunScopeFields {
  readonly threadId: string;
  readonly rootRunId: string;
  readonly runId: string;
  readonly parentRunId?: string;
  readonly employeeId?: string;
  readonly relation?: AgentRunRelation;
  /** Work semantics of this run (set by the delegate tool when known). */
  readonly workKind?: WorkKind;
}

export interface AgentRunStartedPayload {
  readonly objective: string;
  readonly access: AgentRunAccess;
}

export interface AgentRunDeltaPayload {
  readonly channel: 'content' | 'reasoning';
  readonly delta: string;
}

export interface AgentRunToolPayload {
  readonly toolCallId: string;
  readonly toolName: string;
  readonly status: 'started' | 'completed' | 'failed';
  readonly detail?: string;
  readonly durationMs?: number;
  /**
   * Tool-fact-derived activity category. Optional on the wire: a host MAY stamp
   * it, but the projection falls back to {@link classifyToolActivity} on the
   * tool name, so the category never depends on the model or shell content.
   */
  readonly activityKind?: ActivityKind;
}

export interface AgentRunArtifactPayload {
  readonly title: string;
  readonly ref?: string;
  readonly deliverableId?: string;
  readonly path?: string;
  readonly kind?: string;
  readonly mimeType?: string;
  readonly contentHash?: string;
  readonly sizeBytes?: number;
}

export interface AgentRunApprovalPayload {
  readonly uiRequestId: string;
  readonly title: string;
  readonly message?: string;
}

export interface AgentRunFinishedPayload {
  readonly status: AgentRunStatus;
  readonly summary?: string;
  readonly usage?: AgentRunUsage;
}

/** Self-describing delegation event. Discriminated by `type`. */
export type AgentRunEvent = AgentRunScopeFields &
  (
    | { readonly type: 'run.started'; readonly payload: AgentRunStartedPayload }
    | { readonly type: 'run.delta'; readonly payload: AgentRunDeltaPayload }
    | { readonly type: 'tool.started' | 'tool.completed'; readonly payload: AgentRunToolPayload }
    | { readonly type: 'artifact.created'; readonly payload: AgentRunArtifactPayload }
    | { readonly type: 'approval.requested'; readonly payload: AgentRunApprovalPayload }
    | {
        readonly type: 'run.completed' | 'run.failed' | 'run.cancelled';
        readonly payload: AgentRunFinishedPayload;
      }
  );

/** Persisted run record — mirrors the `agent_runs` row (1:1 with a run). */
export interface AgentRunRecord extends AgentRunScopeFields {
  readonly companyId: string;
  readonly objective: string;
  readonly access: AgentRunAccess;
  readonly status: AgentRunStatus;
  readonly usage?: AgentRunUsage;
  readonly resultSummary?: string;
  readonly startedAt: string;
  readonly finishedAt?: string;
}

/**
 * Ordered (category, keyword-set) table for {@link classifyToolActivity}.
 * Whole-token matching avoids substring false hits (e.g. "budget" ⊅ get,
 * "rebuild" ⊅ build via substring). Earlier entries win on token collisions
 * (e.g. `run_tests` → test, not shell).
 */
const ACTIVITY_KEYWORDS: ReadonlyArray<readonly [ActivityKind, ReadonlySet<string>]> = [
  ['test', new Set(['test', 'tests', 'vitest', 'jest', 'pytest', 'qa'])],
  ['build', new Set(['build', 'compile', 'bundle', 'lint', 'typecheck'])],
  ['edit', new Set(['edit', 'patch', 'replace', 'apply', 'modify', 'refactor'])],
  ['write', new Set(['write', 'create', 'save', 'mkdir', 'touch', 'append'])],
  ['search', new Set(['search', 'grep', 'glob', 'find', 'list', 'ls', 'dir', 'locate'])],
  ['read', new Set(['read', 'cat', 'open', 'preview', 'view', 'fetch', 'get', 'show'])],
  ['shell', new Set(['bash', 'sh', 'shell', 'exec', 'run', 'command', 'cmd', 'terminal'])],
  ['wait', new Set(['wait', 'sleep', 'idle', 'poll'])],
];

/**
 * Classify a tool call into an {@link ActivityKind} from the tool *name* alone.
 *
 * Pure and deterministic: it tokenizes only the tool name (snake_case +
 * camelCase split), never arguments or shell content, so the model can't
 * influence the category and the renderer never has to parse raw tool I/O for
 * choreography. Unknown tools fall back to `inspect` ("looking at a result").
 */
export function classifyToolActivity(toolName: string): ActivityKind {
  const tokens = new Set(
    toolName
      .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
      .toLowerCase()
      .split(/[^a-z0-9]+/)
      .filter(Boolean),
  );
  for (const [kind, keywords] of ACTIVITY_KEYWORDS) {
    for (const token of tokens) {
      if (keywords.has(token)) return kind;
    }
  }
  return 'inspect';
}

/** Coarse rendering family for a tool's rich detail view (D1). */
export type ToolFamily = 'terminal' | 'file' | 'search' | 'generic';

/** Map an {@link ActivityKind} to its rich-view {@link ToolFamily}. */
export function toolFamily(kind: ActivityKind): ToolFamily {
  switch (kind) {
    case 'shell':
    case 'build':
    case 'test':
      return 'terminal';
    case 'read':
    case 'write':
    case 'edit':
      return 'file';
    case 'search':
      return 'search';
    default:
      return 'generic';
  }
}

/**
 * Family-structured detail for a tool event, derived from the opaque `detail`
 * blob so the renderer can show a per-family work view (terminal output / file
 * diff / search hits) instead of a generic string.
 */
export type ToolRichDetail =
  | {
      readonly family: 'terminal';
      readonly command?: string;
      readonly exitCode?: number;
      readonly outputSummary?: string;
    }
  | { readonly family: 'file'; readonly path?: string; readonly summary?: string }
  | { readonly family: 'search'; readonly query?: string; readonly hitCount?: number }
  | { readonly family: 'generic'; readonly text?: string };

function parseDetailValue(detail?: string): unknown {
  if (!detail) return null;
  try {
    return JSON.parse(detail) as unknown;
  } catch {
    return null;
  }
}

function pickString(...values: unknown[]): string | undefined {
  for (const v of values) {
    if (typeof v === 'string' && v.length > 0) return v;
  }
  return undefined;
}

function pickRecord(value: unknown): Record<string, unknown> | null {
  return value && typeof value === 'object' && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : null;
}

function pickRecordFrom(value: unknown): Record<string, unknown> | null {
  const record = pickRecord(value);
  if (record) return record;
  if (!Array.isArray(value)) return null;
  for (const item of value) {
    const itemRecord = pickRecord(item);
    if (itemRecord) return itemRecord;
  }
  return null;
}

function pickNumber(...values: unknown[]): number | undefined {
  for (const v of values) {
    if (typeof v === 'number' && Number.isFinite(v)) return v;
  }
  return undefined;
}

function contentTextFrom(value: unknown): string | undefined {
  if (typeof value === 'string' && value.trim()) return value;
  if (Array.isArray(value)) {
    const text = value
      .map((part) => {
        if (typeof part === 'string') return part;
        const record = pickRecord(part);
        return record && typeof record.text === 'string' ? record.text : '';
      })
      .filter(Boolean)
      .join('\n')
      .trim();
    return text || undefined;
  }
  const record = pickRecord(value);
  if (!record) return undefined;
  return pickString(
    record.stdout,
    record.output,
    record.text,
    record.content,
    contentTextFrom(record.content),
  );
}

function summarize(value: unknown, max = 200): string | undefined {
  const text =
    contentTextFrom(value) ?? (value == null ? undefined : JSON.stringify(value));
  if (!text) return undefined;
  const firstLine = text.split('\n')[0] ?? text;
  return firstLine.length > max ? `${firstLine.slice(0, max)}…` : firstLine;
}

/**
 * Parse a tool event's opaque `detail` JSON (the host emits `JSON.stringify` of
 * the tool args on `started` and the result on `completed`) into a
 * family-structured {@link ToolRichDetail}. Pure, deterministic, defensive: an
 * unparseable / key-absent detail degrades to the family with empty fields and
 * never throws. Key names are matched loosely (command/cmd, path/file_path/…,
 * pattern/query/…) because the exact tool arg/result shape varies by tool.
 */
export function parseToolRichDetail(toolName: string, detail?: string): ToolRichDetail {
  const family = toolFamily(classifyToolActivity(toolName));
  const detailValue = parseDetailValue(detail);
  const d = pickRecord(detailValue);
  const input = pickRecordFrom(d?.input);
  const argumentsValue = pickRecordFrom(d?.arguments ?? d?.args);
  const result = pickRecord(d?.result);
  const details = pickRecord(d?.details);
  if (family === 'terminal') {
    return {
      family,
      command: d
        ? pickString(
            d.command,
            d.cmd,
            input?.command,
            input?.cmd,
            argumentsValue?.command,
            argumentsValue?.cmd,
          )
        : undefined,
      exitCode: d
        ? pickNumber(
            d.exitCode,
            d.exit_code,
            d.code,
            input?.exitCode,
            input?.exit_code,
            result?.exitCode,
            result?.exit_code,
            result?.code,
            details?.exitCode,
            details?.exit_code,
            details?.code,
          )
        : undefined,
      outputSummary: d
        ? summarize(d.stdout ?? d.output ?? d.result ?? d.text ?? d.content)
        : undefined,
    };
  }
  if (family === 'file') {
    return {
      family,
      path: d
        ? pickString(
            d.path,
            d.file_path,
            d.filePath,
            d.file,
            input?.path,
            input?.file_path,
            input?.filePath,
            input?.file,
            argumentsValue?.path,
            argumentsValue?.file_path,
            argumentsValue?.filePath,
            argumentsValue?.file,
          )
        : undefined,
      summary: d ? summarize(d.diff ?? d.summary ?? d.result ?? d.text ?? d.content) : undefined,
    };
  }
  if (family === 'search') {
    const hitCount = d
      ? (pickNumber(d.count, d.hits) ??
        (Array.isArray(d.matches)
          ? d.matches.length
          : Array.isArray(d.results)
            ? d.results.length
            : undefined))
      : undefined;
    return {
      family,
      query: d
        ? pickString(
            d.pattern,
            d.query,
            d.regex,
            input?.pattern,
            input?.query,
            input?.regex,
            argumentsValue?.pattern,
            argumentsValue?.query,
            argumentsValue?.regex,
          )
        : undefined,
      hitCount,
    };
  }
  return { family: 'generic', text: summarize(detail) };
}

/**
 * Delegation tool input. `executionMode: 'single'` runs exactly one child and
 * awaits it; `'parallel'` fans out one or more concurrently. `relation` is the
 * parent-child semantics of each task (defaulting to `review` only for
 * review-like tasks, else `delegate`) and is independent of the fan-out mode.
 */
export interface DelegateTaskInput {
  readonly employeeId: string;
  readonly objective: string;
  readonly access: AgentRunAccess;
  /** Optional work semantics for the delegated run (flows to `AgentRunEvent.workKind`). */
  readonly workKind?: WorkKind;
  /** Optional parent-child relation; resolved to a default when omitted. */
  readonly relation?: AgentRunRelation;
}

export interface DelegateToolInput {
  readonly tasks: readonly DelegateTaskInput[];
  readonly executionMode: DelegateExecutionMode;
}
