/**
 * Neutral multi-agent delegation contract.
 *
 * `AgentRunEvent` is the agent-agnostic vocabulary for the run tree: who
 * delegated to whom, what each run is doing, and how each run ends. It rides the
 * runtime event bus as a single `agent.run` family event whose payload is this
 * self-describing envelope (consumers switch on `payload.type`). No `pi_agent_*`
 * term crosses into this layer — the Pi host is one possible producer, never the
 * vocabulary.
 *
 * The run tree is rebuilt purely from the scope fields (`runId / parentRunId /
 * rootRunId`), so a child run can be grafted under its parent without any
 * out-of-band ordering. `rootRunId` is the user-turn run (the controller
 * `attemptId`); the root agent keeps its existing event stream and is the tree
 * root. `runId` is minted per child by the supervisor, consistent with
 * `RunScope`'s per-run identity model (see `../run-scope.ts`).
 *
 * See `Docs/DELEGATION_ARCHITECTURE.md` for the full architecture.
 */

/**
 * How a run relates to its parent — a parent-child *relation*, never a fan-out
 * shape. `delegate` hands off a bounded subtask; `review` is a check of prior
 * work. Specialist takeover (transferring the user conversation) is a later epic
 * and is intentionally NOT a relation value yet — exposing a `handoff` the
 * runtime can't honor only misleads the model. Parallel vs serial is
 * {@link DelegateExecutionMode}, not a relation.
 */
export type AgentRunRelation = 'delegate' | 'review';

/** How a delegate tool call fans out: one awaited child, or several concurrent. */
export type DelegateExecutionMode = 'single' | 'parallel';

/** Terminal + in-flight states a run can be in. */
export type AgentRunStatus = 'running' | 'completed' | 'failed' | 'cancelled';

/** Capability band a delegated run is granted. */
export type AgentRunAccess = 'read' | 'write' | 'review';

/**
 * The semantic *kind of work* a run performs — the delegate tool's operational
 * semantics, not an animation. A short enum used for employee matching, tool /
 * workspace policy, output contracts, and (downstream) dramaturgy. Optional:
 * absent means "unclassified", never a fabricated default.
 */
export type WorkKind =
  | 'plan'
  | 'research'
  | 'design'
  | 'implement'
  | 'review'
  | 'test'
  | 'compute'
  | 'publish'
  | 'present'
  | 'coordinate';

/**
 * The category of a single tool call, derived from tool *facts* (the tool name)
 * by the host/projection — never generated by the model and never parsed from
 * raw shell content. Renderers receive this safe category, not tool internals.
 */
export type ActivityKind =
  | 'read'
  | 'search'
  | 'write'
  | 'edit'
  | 'shell'
  | 'build'
  | 'test'
  | 'inspect'
  | 'wait';

/**
 * Typed cause of a failed run. Stamped by the EMITTER from the structurally
 * known failure site (provider error, timeout, cap refusal, …) — never parsed
 * out of summary text. Present on a run-finished payload iff
 * `status === 'failed'`; completed/cancelled runs never carry it.
 */
export type RunFailureKind = 'token' | 'budget' | 'permission' | 'context' | 'runtime' | 'tool';

/**
 * Classify a provider/model failure message into a typed RunFailureKind at the
 * point where the free text ORIGINATES (a root run's host error, a session
 * error stop). This is the only place failure text may be interpreted — the
 * wire carries the typed kind from here on and no downstream consumer
 * re-parses summaries. Mirror of `classifyRunFailure` in
 * scripts/pi-agent-host-wire.mjs (the bundled .mjs host cannot import TS);
 * the two are locked equal by a harness parity check. Order matters:
 * context-window messages usually mention "tokens", so the context test runs
 * before the token test. Unrecognized text is host/provider machinery →
 * 'runtime'.
 */
export function classifyRunFailure(message: string | undefined | null): RunFailureKind {
  const text = typeof message === 'string' ? message.toLowerCase() : '';
  if (/(context|prompt)[^.]{0,40}(length|window|too long|exceed)|\bcompact/.test(text)) {
    return 'context';
  }
  if (/\btokens?\b|quota|rate.?limit|\b429\b/.test(text)) return 'token';
  if (/permission|unauthorized|forbidden|denied|\b401\b|\b403\b/.test(text)) return 'permission';
  if (/budget|cost.?limit|spend.?limit/.test(text)) return 'budget';
  return 'runtime';
}

export type AgentRunEventType =
  | 'run.started'
  | 'run.delta' // child token stream (content | reasoning)
  | 'tool.started'
  | 'tool.completed' // carries status: completed | failed
  | 'artifact.created'
  | 'approval.requested'
  | 'computer.target.selected'
  // Wire contract only (protocol v5): no producer emits this yet. The live
  // safety gate for computer-use today is the write-class MCP approval flow;
  // driver-signalled sensitive pauses are future work.
  | 'computer.sensitive.paused'
  | 'run.completed'
  | 'run.failed'
  | 'run.cancelled';

export type AgentRunCost =
  | {
      readonly kind: 'actual';
      readonly amountUsd: number;
      readonly source: string;
      readonly capturedAt: string;
    }
  | {
      readonly kind: 'estimate';
      readonly amountUsd: number;
      readonly sourceUrl: string;
      readonly checkedAt: string;
    }
  | {
      readonly kind: 'unavailable';
      readonly reason: string;
      /** Proven subtotal when only part of an aggregate has a usable price. */
      readonly knownAmountUsd?: number;
      readonly knownContributions?: number;
      readonly totalContributions?: number;
    };

export type AgentRunAccountingScope =
  | {
      readonly kind: 'api-run';
      readonly engineId: string;
      readonly accountId: string;
      readonly modelId: string;
    }
  | {
      /** Run telemetry only; never provider-plan Usage and never a dollar-cost source. */
      readonly kind: 'subscription-run-diagnostic';
      readonly engineId: string;
      readonly accountId: string;
      readonly modelId: string;
    };

/**
 * Rolled-up accounting for one run (and, aggregated, its subtree).
 * Missing numeric fields stay absent. `input` excludes cache buckets while
 * `output` includes reasoning, so totals never count either detail twice.
 */
export interface AgentRunUsage {
  readonly scope: AgentRunAccountingScope;
  readonly input?: number;
  readonly output?: number;
  readonly cacheRead?: number;
  readonly cacheWrite?: number;
  readonly reasoning?: number;
  readonly turns?: number;
  readonly inputAccounting: 'excludes-cache';
  readonly outputAccounting: 'includes-reasoning';
  readonly usageSource: {
    readonly kind: 'provider' | 'adapter';
    readonly capturedAt: string;
    readonly reference?: string;
  };
  readonly cost: AgentRunCost;
}

/** One employee available to the Pi delegation supervisor. Model selection is
 * employee-owned: delegate tool input never carries a per-task model override. */
export interface DelegationRosterEntry {
  readonly employeeId: string;
  readonly name: string;
  readonly roleSlug: string;
  readonly persona: string;
  /** Human role title from the employee's persona (e.g. "Orchestrator");
   *  shown to the root agent in the teammate roster instead of the raw slug. */
  readonly displayTitle?: string;
  readonly model?: string;
  readonly thinkingLevel?: string;
  /** Absolute vault SKILL.md paths resolved by the renderer for this employee.
   * Pi's native resource loader reads these when it creates the child session. */
  readonly skillPaths?: readonly string[];
  /** Project-root-relative SKILL.md paths. The Pi child resolves these against
   * its effective worktree so delegated runs keep repository-owned skills. */
  readonly projectSkillPaths?: readonly string[];
}

/** Scope fields present on every event — the run tree is rebuilt from these. */
export interface AgentRunScopeFields {
  readonly threadId: string;
  readonly rootRunId: string;
  readonly runId: string;
  readonly parentRunId?: string;
  readonly employeeId?: string;
  readonly relation?: AgentRunRelation;
  /** Work semantics of this run (set by the delegate tool when known). */
  readonly workKind?: WorkKind;
}

export interface AgentRunStartedPayload {
  readonly objective: string;
  readonly access: AgentRunAccess;
  readonly projectId?: string | null;
  readonly runtimeContextJson?: string | null;
}

export interface AgentRunDeltaPayload {
  readonly channel: 'content' | 'reasoning';
  readonly delta: string;
}

export interface AgentRunToolPayload {
  readonly toolCallId: string;
  readonly toolName: string;
  readonly status: 'started' | 'completed' | 'failed';
  readonly detail?: string;
  readonly durationMs?: number;
  /**
   * Tool-fact-derived activity category. Optional on the wire: a host MAY stamp
   * it, but the projection falls back to {@link classifyToolActivity} on the
   * tool name, so the category never depends on the model or shell content.
   */
  readonly activityKind?: ActivityKind;
}

export interface AgentRunArtifactPayload {
  readonly title: string;
  readonly ref?: string;
  readonly deliverableId?: string;
  readonly path?: string;
  readonly kind?: string;
  readonly mimeType?: string;
  readonly contentHash?: string;
  readonly sizeBytes?: number;
}

export interface AgentRunApprovalPayload {
  readonly uiRequestId: string;
  readonly title: string;
  readonly message?: string;
}

export interface AgentRunComputerTargetPayload {
  readonly targetApp: string;
  readonly targetWindow?: string;
}

export interface AgentRunComputerSensitivePausePayload {
  readonly reason: 'external-navigation' | 'download' | 'credential-field' | 'destructive';
  readonly detail?: string;
}

export interface AgentRunFinishedPayload {
  readonly status: AgentRunStatus;
  readonly summary?: string;
  readonly usage?: AgentRunUsage;
  /** Typed failure cause; present iff `status === 'failed'`. */
  readonly failureKind?: RunFailureKind;
}

/** Self-describing delegation event. Discriminated by `type`. */
export type AgentRunEvent = AgentRunScopeFields &
  (
    | { readonly type: 'run.started'; readonly payload: AgentRunStartedPayload }
    | { readonly type: 'run.delta'; readonly payload: AgentRunDeltaPayload }
    | { readonly type: 'tool.started' | 'tool.completed'; readonly payload: AgentRunToolPayload }
    | { readonly type: 'artifact.created'; readonly payload: AgentRunArtifactPayload }
    | { readonly type: 'approval.requested'; readonly payload: AgentRunApprovalPayload }
    | { readonly type: 'computer.target.selected'; readonly payload: AgentRunComputerTargetPayload }
    | {
        readonly type: 'computer.sensitive.paused';
        readonly payload: AgentRunComputerSensitivePausePayload;
      }
    | {
        readonly type: 'run.completed' | 'run.failed' | 'run.cancelled';
        readonly payload: AgentRunFinishedPayload;
      }
  );

/** Persisted run record — mirrors the `agent_runs` row (1:1 with a run). */
export interface AgentRunRecord extends AgentRunScopeFields {
  readonly companyId: string;
  readonly objective: string;
  readonly access: AgentRunAccess;
  readonly status: AgentRunStatus;
  readonly usage?: AgentRunUsage;
  readonly resultSummary?: string;
  readonly startedAt: string;
  readonly finishedAt?: string;
}

/**
 * Ordered (category, keyword-set) table for {@link classifyToolActivity}.
 * Whole-token matching avoids substring false hits (e.g. "budget" ⊅ get,
 * "rebuild" ⊅ build via substring). Earlier entries win on token collisions
 * (e.g. `run_tests` → test, not shell).
 */
const ACTIVITY_KEYWORDS: ReadonlyArray<readonly [ActivityKind, ReadonlySet<string>]> = [
  ['test', new Set(['test', 'tests', 'vitest', 'jest', 'pytest', 'qa'])],
  ['build', new Set(['build', 'compile', 'bundle', 'lint', 'typecheck'])],
  ['edit', new Set(['edit', 'patch', 'replace', 'apply', 'modify', 'refactor'])],
  ['write', new Set(['write', 'create', 'save', 'mkdir', 'touch', 'append'])],
  ['search', new Set(['search', 'grep', 'glob', 'find', 'list', 'ls', 'dir', 'locate'])],
  ['read', new Set(['read', 'cat', 'open', 'preview', 'view', 'fetch', 'get', 'show'])],
  ['shell', new Set(['bash', 'sh', 'shell', 'exec', 'run', 'command', 'cmd', 'terminal'])],
  ['wait', new Set(['wait', 'sleep', 'idle', 'poll'])],
];

/**
 * Classify a tool call into an {@link ActivityKind} from the tool *name* alone.
 *
 * Pure and deterministic: it tokenizes only the tool name (snake_case +
 * camelCase split), never arguments or shell content, so the model can't
 * influence the category and the renderer never has to parse raw tool I/O for
 * choreography. Unknown tools fall back to `inspect` ("looking at a result").
 */
export function classifyToolActivity(toolName: string): ActivityKind {
  const tokens = new Set(
    toolName
      .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
      .toLowerCase()
      .split(/[^a-z0-9]+/)
      .filter(Boolean),
  );
  for (const [kind, keywords] of ACTIVITY_KEYWORDS) {
    for (const token of tokens) {
      if (keywords.has(token)) return kind;
    }
  }
  return 'inspect';
}

/** Coarse rendering family for a tool's rich detail view (D1). */
export type ToolFamily = 'terminal' | 'file' | 'search' | 'browser' | 'computer' | 'generic';

/** Map an {@link ActivityKind} to its rich-view {@link ToolFamily}. */
export function toolFamily(kind: ActivityKind): ToolFamily {
  switch (kind) {
    case 'shell':
    case 'build':
    case 'test':
      return 'terminal';
    case 'read':
    case 'write':
    case 'edit':
      return 'file';
    case 'search':
      return 'search';
    default:
      return 'generic';
  }
}

/**
 * Family-structured detail for a tool event, derived from the opaque `detail`
 * blob so the renderer can show a per-family work view (terminal output / file
 * diff / search hits) instead of a generic string.
 */
export type ToolRichDetail =
  | {
      readonly family: 'terminal';
      readonly command?: string;
      readonly exitCode?: number;
      readonly outputSummary?: string;
    }
  | { readonly family: 'file'; readonly path?: string; readonly summary?: string }
  | { readonly family: 'search'; readonly query?: string; readonly hitCount?: number }
  | {
      readonly family: 'browser';
      readonly url?: string;
      readonly title?: string;
      readonly screenshot?: { readonly mimeType: string; readonly dataRef: string };
    }
  | {
      readonly family: 'computer';
      readonly action?:
        | 'click'
        | 'type'
        | 'key'
        | 'scroll'
        | 'wait'
        | 'screenshot'
        | 'observe'
        | 'drag'
        | 'move';
      readonly targetApp?: string;
      readonly targetWindow?: string;
      readonly url?: string;
      readonly coordinates?: { readonly x: number; readonly y: number };
      readonly textPreview?: string;
      readonly resultState?: 'ok' | 'failed' | 'pending';
      readonly screenshot?: { readonly mimeType: string; readonly dataRef: string };
      readonly artifactPaths?: readonly string[];
    }
  | { readonly family: 'generic'; readonly text?: string };

function parseDetailValue(detail?: string): unknown {
  if (!detail) return null;
  try {
    return JSON.parse(detail) as unknown;
  } catch {
    return null;
  }
}

function pickString(...values: unknown[]): string | undefined {
  for (const v of values) {
    if (typeof v === 'string' && v.length > 0) return v;
  }
  return undefined;
}

function pickRecord(value: unknown): Record<string, unknown> | null {
  return value && typeof value === 'object' && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : null;
}

function pickRecordFrom(value: unknown): Record<string, unknown> | null {
  const record = pickRecord(value);
  if (record) return record;
  if (!Array.isArray(value)) return null;
  for (const item of value) {
    const itemRecord = pickRecord(item);
    if (itemRecord) return itemRecord;
  }
  return null;
}

function pickNumber(...values: unknown[]): number | undefined {
  for (const v of values) {
    if (typeof v === 'number' && Number.isFinite(v)) return v;
  }
  return undefined;
}

function cappedString(value: unknown, max: number): string | undefined {
  if (typeof value !== 'string' || value.length === 0) return undefined;
  const normalized = value.replace(/\s+/g, ' ').trim();
  if (!normalized) return undefined;
  return normalized.length > max ? normalized.slice(0, max) : normalized;
}

const SENSITIVE_KEY_VALUE_PATTERN =
  /\b(password|passwd|pwd|passphrase|secret|token|api[_-]?key|access[_-]?key|client[_-]?secret|private[_-]?key|bearer|authorization)\b(\s*[:=]\s*|\s+)(\S+)/gi;
const SENSITIVE_TOKEN_PATTERN =
  /\b(sk-[A-Za-z0-9_-]{8,}|ghp_[A-Za-z0-9]{8,}|gho_[A-Za-z0-9]{8,}|github_pat_[A-Za-z0-9_]{8,}|xox[baprs]-[A-Za-z0-9-]{8,}|AKIA[0-9A-Z]{12,}|eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{5,}\.[A-Za-z0-9_-]{5,})\b/g;

/** Mask credential-shaped content in computer-use text previews; the raw typed
 * text must never reach the UI or exported traces. Mirrored in
 * `scripts/pi-mcp-bridge-extension.mjs` (emit side). */
function redactSensitiveText(text: string): string {
  return text
    .replace(SENSITIVE_KEY_VALUE_PATTERN, (_match, key: string, sep: string) => `${key}${sep}•••`)
    .replace(SENSITIVE_TOKEN_PATTERN, '•••');
}

function contentTextFrom(value: unknown): string | undefined {
  if (typeof value === 'string' && value.trim()) return value;
  if (Array.isArray(value)) {
    const text = value
      .map((part) => {
        if (typeof part === 'string') return part;
        const record = pickRecord(part);
        return record && typeof record.text === 'string' ? record.text : '';
      })
      .filter(Boolean)
      .join('\n')
      .trim();
    return text || undefined;
  }
  const record = pickRecord(value);
  if (!record) return undefined;
  return pickString(
    record.stdout,
    record.output,
    record.text,
    record.content,
    contentTextFrom(record.content),
  );
}

function summarize(value: unknown, max = 200): string | undefined {
  const text = contentTextFrom(value) ?? (value == null ? undefined : JSON.stringify(value));
  if (!text) return undefined;
  const firstLine = text.split('\n')[0] ?? text;
  return firstLine.length > max ? `${firstLine.slice(0, max)}…` : firstLine;
}

function contentBlocksFrom(value: unknown): unknown[] | null {
  if (Array.isArray(value)) return value;
  const record = pickRecord(value);
  if (!record) return null;
  if (Array.isArray(record.content)) return record.content;
  if (record.result !== undefined) return contentBlocksFrom(record.result);
  if (record.partialResult !== undefined) return contentBlocksFrom(record.partialResult);
  return null;
}

function isImageBlock(value: unknown): value is Record<string, unknown> {
  const record = pickRecord(value);
  return (
    record?.type === 'image' &&
    typeof record.mimeType === 'string' &&
    record.mimeType.startsWith('image/')
  );
}

function screenshotFromImageValue(
  value: unknown,
): { readonly mimeType: string; readonly dataRef: string } | undefined {
  const record = pickRecord(value);
  const mimeType = pickString(record?.mimeType, record?.mime_type);
  if (!mimeType?.startsWith('image/')) return undefined;
  const data = pickString(record?.data);
  const existingRef = pickString(record?.dataRef, record?.data_ref, record?.uri, record?.url);
  const dataRef = data ? `data:${mimeType};base64,${data}` : existingRef;
  return dataRef ? { mimeType, dataRef } : undefined;
}

function textBlocksFrom(blocks: readonly unknown[]): string[] {
  return blocks
    .map((block) => {
      const record = pickRecord(block);
      return record?.type === 'text' && typeof record.text === 'string' ? record.text.trim() : '';
    })
    .filter(Boolean);
}

function parseBrowserUrl(texts: readonly string[]): string | undefined {
  const joined = texts.join('\n');
  return joined.match(/https?:\/\/[^\s)"'<>]+/i)?.[0];
}

function parseBrowserTitle(texts: readonly string[], url?: string): string | undefined {
  for (const text of texts) {
    const parsed = pickRecord(parseDetailValue(text));
    const fromJson = pickString(parsed?.title, parsed?.pageTitle);
    if (fromJson) return fromJson;
    for (const line of text
      .split('\n')
      .map((l) => l.trim())
      .filter(Boolean)) {
      const labelled = line.match(/^(?:title|pageTitle)\s*[:=-]\s*(.+)$/i)?.[1]?.trim();
      if (labelled) return labelled;
    }
  }
  return texts
    .flatMap((text) =>
      text
        .split('\n')
        .map((line) => line.trim())
        .filter(Boolean),
    )
    .find((line) => line !== url && !/^https?:\/\//i.test(line) && line.length <= 160);
}

function browserDetailFrom(value: unknown): Extract<ToolRichDetail, { family: 'browser' }> | null {
  const blocks = contentBlocksFrom(value);
  if (!blocks) return null;
  const image = blocks.find(isImageBlock);
  if (!image) return null;
  const texts = textBlocksFrom(blocks);
  const url = parseBrowserUrl(texts);
  const title = parseBrowserTitle(texts, url);
  const mimeType = image.mimeType as string;
  const data = typeof image.data === 'string' ? image.data : undefined;
  const existingRef = pickString(image.dataRef, image.uri, image.url);
  const dataRef = data ? `data:${mimeType};base64,${data}` : existingRef;
  return {
    family: 'browser',
    ...(url ? { url } : {}),
    ...(title ? { title } : {}),
    ...(dataRef ? { screenshot: { mimeType, dataRef } } : {}),
  };
}

function computerActionFrom(
  value: unknown,
): Extract<ToolRichDetail, { family: 'computer' }>['action'] {
  switch (value) {
    case 'click':
    case 'type':
    case 'key':
    case 'scroll':
    case 'wait':
    case 'screenshot':
    case 'observe':
    case 'drag':
    case 'move':
      return value;
    default:
      return undefined;
  }
}

function computerResultStateFrom(
  value: unknown,
): Extract<ToolRichDetail, { family: 'computer' }>['resultState'] {
  switch (value) {
    case 'ok':
    case 'failed':
    case 'pending':
      return value;
    default:
      return undefined;
  }
}

function computerCoordinatesFrom(
  value: unknown,
): { readonly x: number; readonly y: number } | undefined {
  const record = pickRecord(value);
  const x = pickNumber(record?.x);
  const y = pickNumber(record?.y);
  return x == null || y == null ? undefined : { x, y };
}

function computerDetailFrom(
  value: unknown,
): Extract<ToolRichDetail, { family: 'computer' }> | null {
  const root = pickRecord(value);
  const result = pickRecord(root?.result);
  const partialResult = pickRecord(root?.partialResult);
  const container = pickRecord(root?.computer)
    ? root
    : pickRecord(result?.computer)
      ? result
      : pickRecord(partialResult?.computer)
        ? partialResult
        : null;
  const computer = pickRecord(container?.computer);
  if (!computer) return null;
  const blocks = contentBlocksFrom(container);
  const screenshot =
    screenshotFromImageValue(computer.screenshot) ??
    screenshotFromImageValue(container?.image) ??
    screenshotFromImageValue(blocks?.find(isImageBlock));
  const artifactPaths = Array.isArray(computer.artifactPaths)
    ? computer.artifactPaths.filter(
        (item): item is string => typeof item === 'string' && item.length > 0,
      )
    : undefined;
  return {
    family: 'computer',
    ...(computerActionFrom(computer.action) ? { action: computerActionFrom(computer.action) } : {}),
    ...(pickString(computer.targetApp, computer.target_app)
      ? { targetApp: pickString(computer.targetApp, computer.target_app) }
      : {}),
    ...(pickString(computer.targetWindow, computer.target_window)
      ? { targetWindow: pickString(computer.targetWindow, computer.target_window) }
      : {}),
    ...(pickString(computer.url) ? { url: pickString(computer.url) } : {}),
    ...(computerCoordinatesFrom(computer.coordinates)
      ? { coordinates: computerCoordinatesFrom(computer.coordinates) }
      : {}),
    ...(() => {
      const preview = cappedString(computer.textPreview ?? computer.text_preview, 160);
      return preview ? { textPreview: redactSensitiveText(preview) } : {};
    })(),
    ...(computerResultStateFrom(computer.resultState ?? computer.result_state)
      ? { resultState: computerResultStateFrom(computer.resultState ?? computer.result_state) }
      : {}),
    ...(screenshot ? { screenshot } : {}),
    ...(artifactPaths && artifactPaths.length > 0 ? { artifactPaths } : {}),
  };
}

/**
 * Parse a tool event's opaque `detail` JSON (the host emits `JSON.stringify` of
 * the tool args on `started` and the result on `completed`) into a
 * family-structured {@link ToolRichDetail}. Pure, deterministic, defensive: an
 * unparseable / key-absent detail degrades to the family with empty fields and
 * never throws. Key names are matched loosely (command/cmd, path/file_path/…,
 * pattern/query/…) because the exact tool arg/result shape varies by tool.
 */
export function parseToolRichDetail(toolName: string, detail?: string): ToolRichDetail {
  const family = toolFamily(classifyToolActivity(toolName));
  const detailValue = parseDetailValue(detail);
  const computer = computerDetailFrom(detailValue);
  if (computer) return computer;
  const browser = browserDetailFrom(detailValue);
  if (browser) return browser;
  const d = pickRecord(detailValue);
  const input = pickRecordFrom(d?.input);
  const argumentsValue = pickRecordFrom(d?.arguments ?? d?.args);
  const result = pickRecord(d?.result);
  const details = pickRecord(d?.details);
  if (family === 'terminal') {
    return {
      family,
      command: d
        ? pickString(
            d.command,
            d.cmd,
            input?.command,
            input?.cmd,
            argumentsValue?.command,
            argumentsValue?.cmd,
          )
        : undefined,
      exitCode: d
        ? pickNumber(
            d.exitCode,
            d.exit_code,
            d.code,
            input?.exitCode,
            input?.exit_code,
            result?.exitCode,
            result?.exit_code,
            result?.code,
            details?.exitCode,
            details?.exit_code,
            details?.code,
          )
        : undefined,
      outputSummary: d
        ? summarize(d.stdout ?? d.output ?? d.result ?? d.text ?? d.content)
        : undefined,
    };
  }
  if (family === 'file') {
    return {
      family,
      path: d
        ? pickString(
            d.path,
            d.file_path,
            d.filePath,
            d.file,
            input?.path,
            input?.file_path,
            input?.filePath,
            input?.file,
            argumentsValue?.path,
            argumentsValue?.file_path,
            argumentsValue?.filePath,
            argumentsValue?.file,
          )
        : undefined,
      summary: d ? summarize(d.diff ?? d.summary ?? d.result ?? d.text ?? d.content) : undefined,
    };
  }
  if (family === 'search') {
    const hitCount = d
      ? (pickNumber(d.count, d.hits) ??
        (Array.isArray(d.matches)
          ? d.matches.length
          : Array.isArray(d.results)
            ? d.results.length
            : undefined))
      : undefined;
    return {
      family,
      query: d
        ? pickString(
            d.pattern,
            d.query,
            d.regex,
            input?.pattern,
            input?.query,
            input?.regex,
            argumentsValue?.pattern,
            argumentsValue?.query,
            argumentsValue?.regex,
          )
        : undefined,
      hitCount,
    };
  }
  return { family: 'generic', text: summarize(detail) };
}

export function mergeToolRichDetail(
  previous: ToolRichDetail | undefined,
  next: ToolRichDetail,
): ToolRichDetail {
  if (!previous || previous.family !== next.family) return next;
  if (next.family === 'terminal' && previous.family === 'terminal') {
    return {
      family: 'terminal',
      command: next.command ?? previous.command,
      exitCode: next.exitCode ?? previous.exitCode,
      outputSummary: next.outputSummary ?? previous.outputSummary,
    };
  }
  if (next.family === 'file' && previous.family === 'file') {
    return {
      family: 'file',
      path: next.path ?? previous.path,
      summary: next.summary ?? previous.summary,
    };
  }
  if (next.family === 'search' && previous.family === 'search') {
    return {
      family: 'search',
      query: next.query ?? previous.query,
      hitCount: next.hitCount ?? previous.hitCount,
    };
  }
  if (next.family === 'browser' && previous.family === 'browser') {
    return {
      family: 'browser',
      url: next.url ?? previous.url,
      title: next.title ?? previous.title,
      screenshot: next.screenshot ?? previous.screenshot,
    };
  }
  if (next.family === 'computer' && previous.family === 'computer') {
    return {
      family: 'computer',
      action: next.action ?? previous.action,
      targetApp: next.targetApp ?? previous.targetApp,
      targetWindow: next.targetWindow ?? previous.targetWindow,
      url: next.url ?? previous.url,
      coordinates: next.coordinates ?? previous.coordinates,
      textPreview: next.textPreview ?? previous.textPreview,
      resultState: next.resultState ?? previous.resultState,
      screenshot: next.screenshot ?? previous.screenshot,
      artifactPaths: next.artifactPaths ?? previous.artifactPaths,
    };
  }
  if (next.family === 'generic' && previous.family === 'generic') {
    return { family: 'generic', text: next.text ?? previous.text };
  }
  return next;
}

/**
 * Delegation tool input. `executionMode: 'single'` runs exactly one child and
 * awaits it; `'parallel'` fans out one or more concurrently. `relation` is the
 * parent-child semantics of each task (defaulting to `review` only for
 * review-like tasks, else `delegate`) and is independent of the fan-out mode.
 */
export interface DelegateTaskInput {
  readonly employeeId: string;
  readonly objective: string;
  readonly access: AgentRunAccess;
  /** Optional work semantics for the delegated run (flows to `AgentRunEvent.workKind`). */
  readonly workKind?: WorkKind;
  /** Optional parent-child relation; resolved to a default when omitted. */
  readonly relation?: AgentRunRelation;
}

export interface DelegateToolInput {
  readonly tasks: readonly DelegateTaskInput[];
  readonly executionMode: DelegateExecutionMode;
}
